### ISSUE TITLE
reflective 模式用自己的域名和VPS不行？

### ISSUE THREAD

**Issue by byioi** [Rvn0xsy/Cooolis-ms#11]
是一定要用阿里云的OSS吗？或者是哪个地方需要修改？

**Comment by byioi** [comment]
测试了好多遍读取不到自己网站的文件，然后尝试重写了ReadHttpFile能读取到自己网站文件，再然后我把代码改回原样发现也能正常读取，这真是神奇

**Comment by Rvn0xsy** [comment]
用任何网站都可以，你可以调试一下程序，是建立连接出现错误还是URL没有正常访问？

https://github.com/Rvn0xsy/Cooolis-ms/blob/794ae701f45888069d75448dcf3ed7a713463c15/Cooolis-ms-Loader/Cooolis-ms/source.cpp#L125

这里我写的是建立HTTPS连接，也就是会连接443端口，你可以把环境描述的更详细一些。
