### ISSUE TITLE
请教2个问题

### ISSUE THREAD

**Issue by Annis-bit** [Rvn0xsy/Cooolis-ms#12]
请教2个问题：
1为什么Coolis-ms.exe与msf联动后，进程是rundll32.exe而不是Coolis-ms.exe，是执行successfull = (*DllEntry)((HINSTANCE)code, DLL_PROCESS_ATTACH, 0)后直接进入了dllmain么，我在源码中没有找到有关rundll32.exe的信息，我看执行这句后，msf就收到数据连接成功了，后面的代码也就不执行了.
2如果dllmain中无执行信息，通过MemoryGetProcAddress（）调用相关函数才会执行一下语句是么.
//DllMain = (Module)MemoryGetProcAddress(hModule, cFunctionName);
//hThread = CooolisCreateThread(NULL, NULL, (LPTHREAD_START_ROUTINE)DllMain, NULL, NULL, &dwThread);
//WaitForSingleObject(hThread, INFINITE);
//MemoryFreeLibrary(hModule);
//return VOID();

**Comment by Rvn0xsy** [comment]
1. rundll32.exe是metasploit自己的payload创建的
2. 是的
