### ISSUE TITLE
有没有联系方式啊，想和师傅沟通下~

### ISSUE THREAD

**Issue by F4ckY0u1** [Rvn0xsy/Cooolis-ms#18]
✈@golangniu 有没有联系方式啊，想和师傅沟通下~

**Comment by Rvn0xsy** [comment]
什么问题

 ------------------原始邮件 ------------------
发件人：F4ckY0u1 ***@***.***>
日期：2023-06-05 下午4:54:22
收件人：Rvn0xsy/Cooolis-ms ***@***.***>
抄送：Subscribed ***@***.***>
主题：[Rvn0xsy/Cooolis-ms] 有没有联系方式啊，想和师傅沟通下~ (Issue #18)
***@***.*** 有没有联系方式啊，想和师傅沟通下~
