### ISSUE TITLE
我想问一下，编译出来的文件大小差很多，是我的vs的文件不够吗，麻烦了

### ISSUE THREAD

**Issue by hllcaiji123** [Rvn0xsy/Cooolis-ms#7]
![图片](https://user-images.githubusercontent.com/48373038/71305745-1f84d900-2413-11ea-9ebc-3501aa56c010.png)

**Comment by Rvn0xsy** [comment]
使用Release模式编译，并且运行库选为”/MT“

![image](https://user-images.githubusercontent.com/19944759/72454826-95a31280-37fc-11ea-9b7f-2b1e587847c7.png)
